# This is a generated file. Not intended for manual editing.
services:
  booker.api:
    build:
      context: "C:\\MalinaSoft\\Booker"
      dockerfile: "C:\\MalinaSoft\\Booker\\Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    ports:
    - "127.0.0.1:57019:57100"
    - "127.0.0.1:57219:57300"
    volumes:
    - "C:\\Users\\Dell\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Dell\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_04_19_50_43:/var/opt/rider-debugger:rw"
